#!/bin/sh
set -e
# Automatically added by dh_installmodules
if [ "$1" = "configure" ]; then
	if [ -e /boot/System.map-4.4.0-cip-uc8100a_me+ ]; then
		depmod -a -F /boot/System.map-4.4.0-cip-uc8100a_me+ 4.4.0-cip-uc8100a_me+ || true
	fi
fi
# End automatically added section
