#!/bin/bash
#
# SPDX-License-Identifier: Apache-2.0
#
# Authors:
# 	2018	Wes Huang	<Wes.Huang@moxa.com>
# 	2019	Fero JD Zhou	<FeroJD.Zhou@moxa.com>
# 	2020	Ken CJ Chou	<KenCJ.Chou@moxa.com>

rfs_resize() {
	expand2fs
	mv /sbin/expand2fs /sbin/expand2fs.bak
	sync
	/sbin/reboot -d -f -i
}

init_gpio() {
	local gpio=${1}
	local direction=${2}
	local value=${3}

	if [ ! -e "/sys/class/gpio/gpio${gpio}" ]; then
		echo "${gpio}" > "/sys/class/gpio/export"
		echo "${direction}" > "/sys/class/gpio/gpio${gpio}/direction"
	fi
	if [ "${direction}" = "out" ]; then
		echo "${value}" > "/sys/class/gpio/gpio${gpio}/value"
	fi
}

get_model_name() {
	local model_name="$(mx-ver -m | awk '{print $1}')"

	case ${model_name} in
	UC-8112A-ME-T-LX)
		model_name="UC-8100A-ME-T-LX"
		;;
	UC-8112A-ME-T-LX-US)
		model_name="UC-8100A-ME-T-LX-US"
		;;
	UC-8112A-ME-T-LX-EU)
		model_name="UC-8100A-ME-T-LX-EU"
		;;
	UC-8112A-ME-T-LX-AP)
		model_name="UC-8100A-ME-T-LX-AP"
		;;
	esac

	echo "${model_name}"
}

one_time_setting() {
	# Enable fcsk for root partition
	fw_setenv robust 1
}

initial_wifi() {
	if dmesg | grep -qE "idProduct=9378|idProduct=b82c"; then
		systemctl start moxa-wifi-signald.service
	fi
}

initial_cellular() {
	systemctl start moxa-cellular-utils.service
	systemctl start moxa-cellular-signald.service
}

initial_tpm2() {
	local tpm2="$(fw_printenv -n tpm2 2>/dev/null)"

	if [ "${tpm2}" = "1" ]; then
		export TPM2TOOLS_TCTI_NAME=device
		export TPM2TOOLS_DEVICE_FILE=/dev/tpmrm0
		init_gpio "112" "in"
		modprobe tpm_spi_tis
	fi
}

uc8100a_me_initial() {
	local model_name="$(get_model_name)"

	# only needs to initial one time
	if [ -f /sbin/expand2fs ]; then
		one_time_setting
		rfs_resize
	fi

	mx-module-ctl -s 1 -p on
	case ${model_name} in
	UC-8100A-ME-T-LX)
		initial_cellular
		initial_wifi
		;;
	UC-8100A-ME-T-LX-US|UC-8100A-ME-T-LX-EU|UC-8100A-ME-T-LX-AP)
		initial_cellular
		;;
	*)
		echo "unknown model name."
		;;
	esac

	initial_tpm2
}

umount_rfs() {
	umount -f -l /tmp
	umount -f -l /home
	umount -f -l /media
	umount -f -l /mnt
	umount -f -l /etc
	umount -f -l /root
	umount -f -l /opt
	umount -f -l /usr
	umount -f -l /bin
	umount -f -l /sbin
	umount -f -l /lib
	umount -f -l /var
	umount -f -l /overlayfs
}

stop_wireless() {
	cell_mgmt stop
	wifi_mgmt stop
	if lsmod | grep "^wlan" -q; then
		rmmod wlan
	fi
	mx-module-ctl -s 1 -p off
}

uc8100a_me_stop() {
	stop_wireless
	umount_rfs
}

case "$1" in
start)
	uc8100a_me_initial
	;;
restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
stop)
	uc8100a_me_stop
	;;
*)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac
exit 0
